version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - '8000:8000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/user-service
      - PORT = 8000

  post-service:
    build: ./post-service
    ports:
      - '8001:8001'
    environment:
      - MONGO_URI=mongodb://mongo:27017/post-service
      - PORT = 8001

  api-gateway:
    build: ./api-gateway
    ports:
      - '8080:8080'

  mongo:
    image: mongo:4.4.6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
